version: 1
accounts:
- name: alice
  coins:
  - 20000token
  - 200000000stake
- name: bob
  coins:
  - 10000token
  - 100000000stake
- name: star
  coins:
  - 10000token
  - 100000000stake
- name: jack
  coins:
  - 10000token
  - 100000000stake
- name: peter
  coins:
  - 10000token
  - 100000000stake
- name: sarah
  coins:
  - 10000token
  - 100000000stake
- name: sahar
  coins:
  - 10000token
  - 100000000stake
- name: bahar
  coins:
  - 10000token
  - 100000000stake
- name: negar
  coins:
  - 10000token
  - 100000000stake
- name: sima
  coins:
  - 10000token
  - 100000000stake
- name: nahid
  coins:
  - 10000token
  - 100000000stake
- name: sepid
  coins:
  - 10000token
  - 100000000stake
- name: sama
  coins:
  - 10000token
  - 100000000stake
- name: sadaf
  coins:
  - 10000token
  - 100000000stake
- name: david
  coins:
  - 10000token
  - 100000000stake
- name: dina
  coins:
  - 10000token
  - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
validators:
- name: alice
  bonded: 100000000stake
