// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dkg/dkg/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgRefundMsgRequest struct {
	Creator      string                                        `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Sender       github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,2,opt,name=sender,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"sender,omitempty"`
	InnerMessage *types.Any                                    `protobuf:"bytes,3,opt,name=inner_message,json=innerMessage,proto3" json:"inner_message,omitempty"`
}

func (m *MsgRefundMsgRequest) Reset()         { *m = MsgRefundMsgRequest{} }
func (m *MsgRefundMsgRequest) String() string { return proto.CompactTextString(m) }
func (*MsgRefundMsgRequest) ProtoMessage()    {}
func (*MsgRefundMsgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a4aecb3c66a91d8, []int{0}
}
func (m *MsgRefundMsgRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRefundMsgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRefundMsgRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRefundMsgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRefundMsgRequest.Merge(m, src)
}
func (m *MsgRefundMsgRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgRefundMsgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRefundMsgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRefundMsgRequest proto.InternalMessageInfo

func (m *MsgRefundMsgRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgRefundMsgRequest) GetSender() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *MsgRefundMsgRequest) GetInnerMessage() *types.Any {
	if m != nil {
		return m.InnerMessage
	}
	return nil
}

type MsgRefundMsgRequestResponse struct {
}

func (m *MsgRefundMsgRequestResponse) Reset()         { *m = MsgRefundMsgRequestResponse{} }
func (m *MsgRefundMsgRequestResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRefundMsgRequestResponse) ProtoMessage()    {}
func (*MsgRefundMsgRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a4aecb3c66a91d8, []int{1}
}
func (m *MsgRefundMsgRequestResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRefundMsgRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRefundMsgRequestResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRefundMsgRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRefundMsgRequestResponse.Merge(m, src)
}
func (m *MsgRefundMsgRequestResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRefundMsgRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRefundMsgRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRefundMsgRequestResponse proto.InternalMessageInfo

type MsgFileDispute struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *MsgFileDispute) Reset()         { *m = MsgFileDispute{} }
func (m *MsgFileDispute) String() string { return proto.CompactTextString(m) }
func (*MsgFileDispute) ProtoMessage()    {}
func (*MsgFileDispute) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a4aecb3c66a91d8, []int{2}
}
func (m *MsgFileDispute) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFileDispute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFileDispute.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFileDispute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFileDispute.Merge(m, src)
}
func (m *MsgFileDispute) XXX_Size() int {
	return m.Size()
}
func (m *MsgFileDispute) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFileDispute.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFileDispute proto.InternalMessageInfo

func (m *MsgFileDispute) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type MsgFileDisputeResponse struct {
}

func (m *MsgFileDisputeResponse) Reset()         { *m = MsgFileDisputeResponse{} }
func (m *MsgFileDisputeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgFileDisputeResponse) ProtoMessage()    {}
func (*MsgFileDisputeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a4aecb3c66a91d8, []int{3}
}
func (m *MsgFileDisputeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFileDisputeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFileDisputeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFileDisputeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFileDisputeResponse.Merge(m, src)
}
func (m *MsgFileDisputeResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgFileDisputeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFileDisputeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFileDisputeResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRefundMsgRequest)(nil), "dkg.dkg.MsgRefundMsgRequest")
	proto.RegisterType((*MsgRefundMsgRequestResponse)(nil), "dkg.dkg.MsgRefundMsgRequestResponse")
	proto.RegisterType((*MsgFileDispute)(nil), "dkg.dkg.MsgFileDispute")
	proto.RegisterType((*MsgFileDisputeResponse)(nil), "dkg.dkg.MsgFileDisputeResponse")
}

func init() { proto.RegisterFile("dkg/dkg/tx.proto", fileDescriptor_1a4aecb3c66a91d8) }

var fileDescriptor_1a4aecb3c66a91d8 = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xc1, 0xce, 0xd2, 0x40,
	0x10, 0x66, 0x25, 0x81, 0xb8, 0x20, 0x92, 0x4a, 0xb4, 0x54, 0x2d, 0xa4, 0xf1, 0x80, 0x26, 0x6c,
	0x23, 0x3e, 0x01, 0xc4, 0x68, 0x38, 0xf4, 0xd2, 0x83, 0x07, 0x2f, 0xa4, 0xed, 0x0e, 0x6b, 0x53,
	0xe8, 0xd6, 0x4e, 0x9b, 0xc0, 0x5b, 0xf8, 0x14, 0x3e, 0x81, 0xaf, 0x60, 0x62, 0x3c, 0x71, 0xf4,
	0x64, 0x0c, 0xbc, 0x85, 0xa7, 0x3f, 0xed, 0xb6, 0x09, 0x7f, 0x7e, 0xf8, 0x0f, 0x9b, 0x9d, 0x99,
	0x6f, 0xe6, 0xcb, 0x7c, 0x33, 0x43, 0xfb, 0x3c, 0x12, 0x76, 0xf1, 0xb2, 0x1d, 0x4b, 0x52, 0x99,
	0x49, 0xad, 0xcd, 0x23, 0xc1, 0x78, 0x24, 0x8c, 0xa1, 0x90, 0x52, 0x6c, 0xc0, 0x2e, 0xc3, 0x7e,
	0xbe, 0xb6, 0xbd, 0x78, 0xaf, 0x72, 0x8c, 0x81, 0x90, 0x42, 0x96, 0xa6, 0x5d, 0x58, 0x55, 0x74,
	0x18, 0x48, 0xdc, 0x4a, 0x5c, 0x29, 0x40, 0x39, 0x0a, 0xb2, 0x7e, 0x12, 0xfa, 0xc4, 0x41, 0xe1,
	0xc2, 0x3a, 0x8f, 0x79, 0x69, 0x7c, 0xcd, 0x01, 0x33, 0x4d, 0xa7, 0xed, 0x20, 0x05, 0x2f, 0x93,
	0xa9, 0x4e, 0xc6, 0x64, 0xf2, 0xd0, 0xad, 0x5d, 0x6d, 0x49, 0x5b, 0x08, 0x31, 0x87, 0x54, 0x7f,
	0x30, 0x26, 0x93, 0xee, 0xe2, 0xed, 0xff, 0xbf, 0xa3, 0xa9, 0x08, 0xb3, 0x2f, 0xb9, 0xcf, 0x02,
	0xb9, 0xad, 0xe8, 0xab, 0x6f, 0x8a, 0x3c, 0xb2, 0xb3, 0x7d, 0x02, 0xc8, 0xe6, 0x41, 0x30, 0xe7,
	0x3c, 0x05, 0x44, 0xb7, 0x22, 0xd0, 0x96, 0xf4, 0x51, 0x18, 0xc7, 0x90, 0xae, 0xb6, 0x80, 0xe8,
	0x09, 0xd0, 0x9b, 0x63, 0x32, 0xe9, 0xcc, 0x06, 0x4c, 0x09, 0x64, 0xb5, 0x40, 0x36, 0x8f, 0xf7,
	0x8b, 0xde, 0xef, 0x1f, 0x53, 0xaa, 0xfa, 0xf4, 0xfc, 0x0d, 0xb8, 0xdd, 0xb2, 0xd4, 0x51, 0x95,
	0xd6, 0x4b, 0xfa, 0xfc, 0x82, 0x0c, 0x17, 0x30, 0x91, 0x31, 0x82, 0xf5, 0x86, 0xf6, 0x1c, 0x14,
	0x1f, 0xc2, 0x0d, 0xbc, 0x0f, 0x31, 0xc9, 0x33, 0xb8, 0x2e, 0xd0, 0xd2, 0xe9, 0xd3, 0xdb, 0xb9,
	0x35, 0xcb, 0xec, 0x3b, 0xa1, 0x4d, 0x07, 0x85, 0xf6, 0x89, 0xf6, 0xef, 0x0c, 0xec, 0x05, 0xab,
	0xd6, 0xc3, 0x2e, 0xf4, 0x61, 0xbc, 0xba, 0x0f, 0xad, 0xf9, 0xb5, 0x8f, 0xb4, 0x73, 0xde, 0xe2,
	0xb3, 0xf3, 0xa2, 0x33, 0xc0, 0x18, 0x5d, 0x01, 0x6a, 0xa2, 0xc5, 0xeb, 0x5f, 0x47, 0x93, 0x1c,
	0x8e, 0x26, 0xf9, 0x77, 0x34, 0xc9, 0xb7, 0x93, 0xd9, 0x38, 0x9c, 0xcc, 0xc6, 0x9f, 0x93, 0xd9,
	0xf8, 0xfc, 0xb8, 0x38, 0xa9, 0x9d, 0x3a, 0xac, 0x62, 0x2d, 0x7e, 0xab, 0x1c, 0xf2, 0xbb, 0x9b,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x81, 0x28, 0xc5, 0x4a, 0x70, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	RefundMsgRequest(ctx context.Context, in *MsgRefundMsgRequest, opts ...grpc.CallOption) (*MsgRefundMsgRequestResponse, error)
	FileDispute(ctx context.Context, in *MsgFileDispute, opts ...grpc.CallOption) (*MsgFileDisputeResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RefundMsgRequest(ctx context.Context, in *MsgRefundMsgRequest, opts ...grpc.CallOption) (*MsgRefundMsgRequestResponse, error) {
	out := new(MsgRefundMsgRequestResponse)
	err := c.cc.Invoke(ctx, "/dkg.dkg.Msg/RefundMsgRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) FileDispute(ctx context.Context, in *MsgFileDispute, opts ...grpc.CallOption) (*MsgFileDisputeResponse, error) {
	out := new(MsgFileDisputeResponse)
	err := c.cc.Invoke(ctx, "/dkg.dkg.Msg/FileDispute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	RefundMsgRequest(context.Context, *MsgRefundMsgRequest) (*MsgRefundMsgRequestResponse, error)
	FileDispute(context.Context, *MsgFileDispute) (*MsgFileDisputeResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RefundMsgRequest(ctx context.Context, req *MsgRefundMsgRequest) (*MsgRefundMsgRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefundMsgRequest not implemented")
}
func (*UnimplementedMsgServer) FileDispute(ctx context.Context, req *MsgFileDispute) (*MsgFileDisputeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileDispute not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RefundMsgRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRefundMsgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RefundMsgRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dkg.dkg.Msg/RefundMsgRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RefundMsgRequest(ctx, req.(*MsgRefundMsgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_FileDispute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgFileDispute)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).FileDispute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dkg.dkg.Msg/FileDispute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).FileDispute(ctx, req.(*MsgFileDispute))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dkg.dkg.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RefundMsgRequest",
			Handler:    _Msg_RefundMsgRequest_Handler,
		},
		{
			MethodName: "FileDispute",
			Handler:    _Msg_FileDispute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dkg/dkg/tx.proto",
}

func (m *MsgRefundMsgRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRefundMsgRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRefundMsgRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.InnerMessage != nil {
		{
			size, err := m.InnerMessage.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRefundMsgRequestResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRefundMsgRequestResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRefundMsgRequestResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgFileDispute) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFileDispute) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFileDispute) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgFileDisputeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFileDisputeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFileDisputeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRefundMsgRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.InnerMessage != nil {
		l = m.InnerMessage.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRefundMsgRequestResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgFileDispute) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgFileDisputeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRefundMsgRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRefundMsgRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRefundMsgRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = append(m.Sender[:0], dAtA[iNdEx:postIndex]...)
			if m.Sender == nil {
				m.Sender = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InnerMessage", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.InnerMessage == nil {
				m.InnerMessage = &types.Any{}
			}
			if err := m.InnerMessage.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRefundMsgRequestResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRefundMsgRequestResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRefundMsgRequestResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgFileDispute) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFileDispute: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFileDispute: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgFileDisputeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFileDisputeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFileDisputeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
